### ISSUE TITLE
Step 3 throws: "Tasks must have an initial Context argument!"

### ISSUE THREAD

**Issue by lvdo** [snowplow/aws-lambda-scala-example-project#11]
When running:
`$ inv create_kinesis_stream my-stream`

I got:

```
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/local/lib/python2.7/dist-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/vagrant/tasks.py", line 81, in <module>
    @task
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 267, in task
    return Task(args[0], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
```

I fixed this by adding a `ctx` argument to all functions in `tasks.py` with an `@task` attribute. Didn't create a PR because I don't understand why I need this and others don't.

**Comment by alexanderdean** [comment]
Assigning to @ninjabear to take a look...

**Comment by chuwy** [comment]
That is because in pyinvoke all tasks must be contextualized since 0.13.0 (released 9th June). And ansible playbook installs last version by default, that is why others didn't need it earlier.
So, I guess we should install older version explicitly in ansible playbook or (preferable) fix it as @lvdo suggested.

**Comment by chuwy** [comment]
And that of course means our other example-projects now are broken as well.

**Comment by alexanderdean** [comment]
@chuwy can we mutate ansible-playbooks to peg the pyinvoke version at a compatible one?

**Comment by chuwy** [comment]
@alexanderdean I guess so. I'll try.
But anyway we need to create tickets in example projects to make them compatible.

**Comment by alexanderdean** [comment]
Thanks @chuwy !

**Comment by chuwy** [comment]
Hey @lvdo. This should work now.

**Comment by lvdo** [comment]
@chuwy yes, it does, thanks! Just started over and another issue I ran into is also fixed.
